Consolidate management
clsavino/react-shift-scheduler pull request #11
Opened 2017-01-01 21:30 UTC by mr-attack

Manager section has been trimmed down and changed
New (and less) routes
New styling reapplied to login and register pages

2017-01-01 23:03 UTC, amr08 requested changes

2017-01-01 23:03 UTC, amr08 commented on app/components/children/Register.js
> +                                        onChange={this.handleUserChange} />
@mr-attack Wondering if user validation still works on your end.   All fields need to end with required in order for the form validation to work  ```required />```  

Also dont forget to test log in (see if you are stored in mongo)

2017-01-02 14:04 UTC, mr-attack commented on app/components/children/Register.js
> +                                        onChange={this.handleUserChange} />
All done

2017-01-02 14:06 UTC, amr08 approved these changes

2017-01-02 14:06 UTC, merged